### PR TITLE
Improved permission suggestions

### PR DESCRIPTION
**Pull request by BrainStone**
So here we are. The suggestions should be much better now.

I sadly couldn't find an option to make so pressing tab added the current selected choice to the search query or that a button appears. If anyone know how to do that, feel free to either let me know so I can add it or add it themselves.

This change goes towards #316 

Technically closes that issue but doesn't take care of the other optional things I mentioned.

### CODE REVIEW

**Comment by BrainStone** [comment]
Can be tested live here: https://editor.project-creative.net/editor/

**Comment by lucko** [comment]
I personally quite liked being able to browse through all available nodes... losing that functionality is a step in the wrong direction imo.



Perhaps another button next to "Press enter to select" which allows that node to be expanded?

In my opinion that needs to be solved before this can be merged.

**Comment by lucko** [comment]
And actually - the "press enter to select" is useless for the nodes which aren't leafs - since (unless you're using Sponge wildcards) they are not going to work as permissions.

**Comment by BrainStone** [comment]
The goal here was to declutter the suggestions because it can become too much too quickly.  
So the idea was to mimic the ingame completion. 

After having used it like that i agree that not being able to select the partial text node makes it almost worse.

**Pull request closed without merging**
